// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQsd3Zqoawd89iNnfElhi-GCYIURhTfes',
    appId: '1:1026944786970:android:c08565a0598d1a835127a3',
    messagingSenderId: '1026944786970',
    projectId: 'flutter-login-kslays40',
    storageBucket: 'flutter-login-kslays40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvcCjaArueBZDUoKjGEr9OEBGwIaEW2qM',
    appId: '1:1026944786970:ios:3f0226df61b707855127a3',
    messagingSenderId: '1026944786970',
    projectId: 'flutter-login-kslays40',
    storageBucket: 'flutter-login-kslays40.appspot.com',
    androidClientId: '1026944786970-dgmvpukbs9tmvnnlne86lrv5m4q9mfl5.apps.googleusercontent.com',
    iosClientId: '1026944786970-ngfrsq9vudtvtiucem3vrbuedikvbf4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskTrial',
  );
}
